'use strict';
const assert=require('node:assert/strict');
const M=require('../js/metrics.js');
const session={weightKg:60,units:[{kind:'exercise',rest:60,reps:'10-12',sets:[{done:true,reps:'10'},{done:true,reps:'10'},{done:false,reps:'12'}]},{kind:'cardio',minutes:10,sets:[{done:false}]},{kind:'warmup',minutes:5,sets:[{done:true}]}]};
const a=M.estimate(session);
assert.equal(a.durationMinutes,7);assert.equal(a.calories,19);assert.equal(a.strengthSets,2);
assert.equal(M.estimate({weightKg:60,units:[]}).calories,0);
assert.equal(M.estimate({units:session.units}).calories,null);
assert.equal(M.estimate({weightKg:90,units:session.units}).calories,28);
session.units[1].sets[0].done=true;
assert.equal(M.estimate(session).durationMinutes,17);assert.equal(M.estimate(session).calories,69);
const logs=[{date:'2026-09-01',calories:100,durationMinutes:20,volume:1000},{date:'2026-09-01',calories:50,durationMinutes:10,volume:500},{date:'2026-09-02',volume:200},{date:'2026-08-30',calories:900},{date:'2026-09-07',calories:900}];
const before=JSON.stringify(logs),points=M.series(logs,7,new Date(2026,8,6));
assert.equal(points.length,7);assert.equal(points[0].date,'2026-08-31');assert.equal(points[6].date,'2026-09-06');
assert.equal(points[1].calories,150);assert.equal(points[1].sessions,2);assert.equal(points[1].volume,1500);
assert.equal(points[2].missing,1);assert.equal(points[2].missingDuration,1);assert.equal(points[3].sessions,0);assert.equal(points[3].missing,0);
assert.equal(JSON.stringify(logs),before);
assert.equal(M.series([],7,new Date(2026,0,2))[0].date,'2025-12-27');
assert.equal(M.finite(null),false);assert.equal(M.finite(NaN),false);
console.log('Metrics checks passed: completed-only estimates, weight snapshot, missing history, same-day sums, date boundaries, no mutation.');
